### ISSUE TITLE
Not able to locate letter `a`

### ISSUE THREAD

**Issue by mrjjwright** [kbrsh/wade#12]
Thanks for this awesome little lib.

In both my own code and the example on the README, nothing comes up when searching for the letter 'a'.

**Comment by kbrsh** [comment]
That's because the letter a is a word as well. It's also a stop word, and Wade removes it from the query.

If you want to remove this step, try:

```js
Wade.pipeline.pop();
```

**Comment by mrjjwright** [comment]
Oh ok, thanks!
