### ISSUE TITLE
Using a Set instead of a Array for stopWords

### ISSUE THREAD

**Issue by SuperAmin** [kbrsh/wade#16]
I was wondering why stopWords is a Array of words instead of a Set (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) since it looks like you're only using it to check if a word in a document/query is contained in stopWords.

**Comment by kbrsh** [comment]
A set would be a better approach in this case, but they are not compatible with older versions of IE. Once most browsers support ES6 and `Set`, they will definitely be used in Wade.
