### ISSUE TITLE
malware linked to in readme

### ISSUE THREAD

**Issue by JayHoltslander** [kbrsh/wade#23]
The link

>Combined with JavaScript libraries like Moon, you can create a **real-time search**.

Leads to the following malicious URL after several redirects

``https://s3.amazonaws.com/2133/_rClCMbQhUGCElagO8/2106/xpFCLbKj?subaff=0154978719681000885978315325068415985317&k=d2ad2ac5-f14b-e911-81f7-ed46f4389d4a&adnet_track=0154978719681000885978315325068415985317&s=8c46e8ca-ed32-4c09-a031-744a7a81ca39&client=safari&kd=aHR0cDovL3d3dy5jb25zb2xlb3BlcmF0aW9uLmNvbQ%253d%253d&h=ShBEQBoNFAYIBggfBwUVBg9gCQQLBwUOCgcYBAwCCQsGBRUHDg4IBxMeFF1IFQwFCgEJBAcFDgAPGBpUEwgUUApWUgZZVAQfUAUMVRtRAQYAHw4FXgAbUVwDB1QCBwAOUgBZFR0QWkRcFQwWUENFQkUOFxhFBxZWXFNMW1ZWQUcWVF5fFBgaRFEWAllEXloYGkdVXRoNBQsHGBpUUkQaDUVAQ1FF&a=1&u=aHR0cHM6Ly9zMy5hbWF6b25hd3MuY29tLzRhMWFmL0ZDQzlBQjE3MEFBMzE3NzY4RjVDOEM1RDExNkEyRENCL2hXaDNoNFE%3d``

**Comment by kbrsh** [comment]
Thanks for letting me know, those links are outdated haha. Will fix ASAP
