### ISSUE TITLE
Multiple stop words in a row will not be deleted

### ISSUE THREAD

**Issue by jeffbaumes** [kbrsh/wade#3]
https://github.com/KingPixil/wade/blob/master/src/index.js#L97

For example, see this test code:

```
> a = [1, 2, 2, 3, 2, 2, 2, 4, 2, 2]
> for(var i = 0; i < a.length; i++) { if (a[i] === 2) { a.splice(i, 1); } }
> a
[1, 2, 3, 2, 4, 2]
```

Adding `i--` in your loop when splicing should fix it:

```
> a = [1, 2, 2, 3, 2, 2, 2, 4, 2, 2]
> for(var i = 0; i < a.length; i++) { if (a[i] === 2) { a.splice(i, 1); i--; } }
> a
[1, 3, 4]
```

**Comment by kbrsh** [comment]
Ahh, you're right. A stop word can be deleted and the next item will be ignored as well. Thanks for reporting!
