### ISSUE TITLE
Fuzzy functionality?

### ISSUE THREAD

**Issue by tannerlinsley** [kbrsh/wade#8]
I'm still not sure I understand how Wade handles searching. Is it possible to do fuzzy searching with Wade?

**Comment by kbrsh** [comment]
Wade doesn't handle fuzzy searching and I do not have plans on adding support for it. It would require a rewrite of most of the searching logic, and would significantly increase the weight (over 1kb).

If this is something you are looking for, I'd suggest [lunr.js](https://github.com/olivernn/lunr.js).

**Comment by tannerlinsley** [comment]
Sounds good. Thanks!
